import requests
import urllib3
import smtplib
from email.message import EmailMessage
from datetime import datetime
import os
import sys

# =========================
# CONFIGURATION SECTION
# =========================

FIREWALL_IP = "150.242.201.80"
API_TOKEN = "3gd5QyQ1bpwtpgy1csG4hqH8nznQ5x"

FIREWALL_NAME = "Audix-FG-60F"

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

EMAIL_ADDRESS = "shrikantpnadgauda@gmail.com"
EMAIL_PASSWORD = "nuqiybwolkskelco"

EMAIL_TO = "shri.gaudaa@gmail.com"

BACKUP_FILENAME = "fortigate_backup.conf"

# =========================

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def download_backup():
    print("🔄 Downloading firewall backup...")

    url = f"https://{FIREWALL_IP}:9443/api/v2/monitor/system/config/backup?scope=global"
    headers = {
        "Authorization": f"Bearer {API_TOKEN}"
    }

    try:
        response = requests.get(url, headers=headers, verify=False, timeout=30)
        print("Status Code:", response.status_code)

        if response.status_code == 200:
            with open(BACKUP_FILENAME, "wb") as f:
                f.write(response.content)

            print("✅ Backup downloaded successfully")
            return True, "Backup completed successfully."
        else:
            print("❌ Backup failed")
            print("Response:", response.text)
            return False, f"Backup failed. HTTP {response.status_code}"

    except Exception as e:
        print("❌ Exception while downloading backup:", str(e))
        return False, f"Exception occurred: {str(e)}"


def send_email(status_message, attachment_path=None):
    print("📧 Sending email...")

    msg = EmailMessage()
    msg["From"] = EMAIL_ADDRESS
    msg["To"] = EMAIL_TO
    msg["Subject"] = f"{FIREWALL_NAME} - Backup & Status Report"

    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    body = f"""
Firewall Name : {FIREWALL_NAME}
Date & Time   : {current_time}
Firewall IP   : {FIREWALL_IP}

Status:
{status_message}

This is an automated email generated by FortiGate Automation Script.
"""

    msg.set_content(body)

    # Attachment
    if attachment_path and os.path.exists(attachment_path):
        with open(attachment_path, "rb") as f:
            file_data = f.read()
            file_name = os.path.basename(attachment_path)

        msg.add_attachment(
            file_data,
            maintype="application",
            subtype="octet-stream",
            filename=file_name
        )

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            server.send_message(msg)

        print("✅ Email sent successfully")

    except Exception as e:
        print("❌ Failed to send email:", str(e))


def main():
    success, status_message = download_backup()

    if success:
        send_email(status_message, BACKUP_FILENAME)
    else:
        send_email(status_message, None)


if __name__ == "__main__":
    main()