import smtplib
from email.message import EmailMessage
import os
from datetime import datetime

SMTP_SERVER = "smtp.zoho.in"
SMTP_PORT = 587
EMAIL_ADDRESS = "shrikant.nadgauda@audixindia.in"
EMAIL_PASSWORD = "Shri$#@12345"

def send_email(firewall_name, status_message, attachment_path=None):

    msg = EmailMessage()

    # ---- Email Header ----
    msg["From"] = EMAIL_ADDRESS
    msg["To"] = "shri.gaudaa@gmail.com"   # <-- yaha apna mail daal
    msg["Subject"] = f"{firewall_name} - Firewall Backup & Status Report"

    # ---- Email Body ----
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    body = f"""
Firewall Name : {firewall_name}
Date & Time   : {current_time}

Status:
{status_message}

This is an automated email generated by Network Automation Script.
"""

    msg.set_content(body)

    # ---- Attachment ----
    if attachment_path and os.path.exists(attachment_path):
        with open(attachment_path, "rb") as f:
            file_data = f.read()
            file_name = os.path.basename(attachment_path)

        msg.add_attachment(
            file_data,
            maintype="application",
            subtype="octet-stream",
            filename=file_name
        )

    # ---- Send Mail ----
    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
        server.starttls()
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        server.send_message(msg)

    print("📧 Email Sent Successfully")